### PR TITLE
Hi. I'd like to collaborate.

### PR DESCRIPTION
**Pull request by ian-kelling**
I'm making quite a few changes. My commits aren't totally tidy and isolated to each change. I don't know how to contact you outside of doing a github pull request. My email is ian at iankelling (.) org.

### CODE REVIEW

**Comment by zk-phi** [comment]
Thanks for the suggestions.
Some questions and comments :
- for commit 887a8a3710ed6ee091bac17770f05ccbc11033f9
  - I thought that inheriting the "'default" face is better (setting slant nil seems a bit ad-hoc)

```
(set-face-attribute 'spray-base-face nil :inherit 'default)
```
- 82ffa7dc81feace23f4244211016e934980053ce
  - why should we remove the argument for "spray-start/stop" function ?
  - (I thought that passing an integer to a toggling function matches emacs conventions -- define-minor-mode, for example)
- dce5a35abd9e640d6d6123ac2b2bfd42c86ee7f8, 0cb0ae4211111aabd624e77621a5758a36499e67 and 64d29d81de55a9b14e8bb390755b0e2b3bbf9eba
  - why making strings considered better than using display properties ?
  - why should we change (1+ []) to (+ 1 []) ?
- 280e554878f25318f94e032f8acde6281905aa2e and 85cc75a5f67c77acdea38c0d23ddf1cf4d83f19b
  - I think we'd better add a customizable variable like "spray-unsupported-minor-modes", instead of hard-coding the minor-modes

thanks.

**Comment by ian-kelling** [comment]
> I thought that inheriting the "'default" face is better (setting slant nil seems a bit ad-hoc)

I agree. It was just a stop gap so I could read some italicized text.

> why should we remove the argument for "spray-start/stop" function ?

I don't mind the argument actually. I didn't like how the code inside was hard to figure out. That change was more of a mental aid for me, to get me going on being invested and caring about the code. edit: - it just seems more readable that way, instead of (do-x/y -1), just say (do-x). This isn't a mode being enabled, so I didn't get it right away. It's no big deal, and I can go with your way if you want. What do you think?

> why making strings considered better than using display properties ?

For the top margin, if we use a tall blank character, it pushes up the overline to the wrong place. By overline, I mean the line just above the accented character, which is like the underline but above. To avoid that, we have to use at least 1 regular height character and then a newline. And then, the code just seemed simpler to use characters, instead of characters and display properties. We can still do both if you want.

> why should we change (1+ []) to (+ 1 []) ?

No reason, I was just tinkering and forgot about changing it back. I will change that.

> I think we'd better add a customizable variable like "spray-unsupported-minor-modes", instead of hard-coding the minor-modes

I agree. Do you want to write that, or should I?

Also, I can make clean logical commits in their own branches and make individual pull requests if you want. A lot of these projects seem to be abandonware, I wanted to make sure you would actually respond before going to the trouble.

**Comment by zk-phi** [comment]
Thanks for the response and additional commits. I understood and merged the changes.
I'll add something like spray-unsupported-minor-modes, and fix spray-base-face later.

> A lot of these projects seem to be abandonware, I wanted to make sure you would actually respond before going to the trouble.

So you think that this project has a risk of being in trouble right?

**Comment by ian-kelling** [comment]
> So you think that this project has a risk of being in trouble right?

A lot of people put out an initial version of software then never touch it again, that's what I meant by abandonware. But you responded, so I don't think that. Do me a favor and send me an email so I can communicate directly with you :)

**Comment by zk-phi** [comment]
Ah, I see. I misunderstood the comment.
I have no email addresses for public use so I cannot send you an email immediately, sorry.

I also added you as a collaborator. Thanks for the contributions.

**Comment by ian-kelling** [comment]
Np. Thank you. I will try to make cleaner commits in the future. Do you mean you don't want to publish your email address publicly? If that is what you mean, you can email me and ian@iankelling (.) org, then I will have your email address and I won't publish it. If not, do you have some other way to talk? IRC?

**Comment by zk-phi** [comment]
okay, sent an email.

**Pull request merged**
